version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper-aws
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka-aws
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
