name: Deploy to Aws

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select The environment
        default: dev
        required: true
      release-build:
        type: boolean
        description: Wheather is this a release build?
        default: false
jobs:
  deploy:
    runs-on: aws-ec2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Java 17
      run: |
        sudo amazon-linux-extras install java-openjdk17
        echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.0.35-2.x86_64' >> $GITHUB_ENV
        echo 'export PATH=$PATH:$JAVA_HOME/bin' >> $GITHUB_ENV
        source $GITHUB_ENV  
    - name: Install Maven
      run: sudo yum install -y maven  
      
    - name: Build Spring Boot App
      run: mvn clean install
