name: Deploy to Aws

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select The environment
        default: dev
        required: true
      release-build:
        type: boolean
        description: Wheather is this a release build?
        default: false

